/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSifayntaRouteImport } from './routes/_app.sifaynta'
import { Route as AppShaqaalahaRouteImport } from './routes/_app.shaqaalaha'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppMaaliyaddaRouteImport } from './routes/_app.maaliyadda'
import { Route as AppKalandarRouteImport } from './routes/_app.kalandar'
import { Route as AppIsticmaalayaashaRouteImport } from './routes/_app.isticmaalayaasha'
import { Route as AppImtixaanadaRouteImport } from './routes/_app.imtixaanada'
import { Route as AppGaadiidkaRouteImport } from './routes/_app.gaadiidka'
import { Route as AppFasalladaRouteImport } from './routes/_app.fasallada'
import { Route as AppDacwoRouteImport } from './routes/_app.dacwo'
import { Route as AppCasharkaRouteImport } from './routes/_app.casharka'
import { Route as AppArdaydaRouteImport } from './routes/_app.ardayda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSifayntaRoute = AppSifayntaRouteImport.update({
  id: '/sifaynta',
  path: '/sifaynta',
  getParentRoute: () => AppRoute,
} as any)
const AppShaqaalahaRoute = AppShaqaalahaRouteImport.update({
  id: '/shaqaalaha',
  path: '/shaqaalaha',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMaaliyaddaRoute = AppMaaliyaddaRouteImport.update({
  id: '/maaliyadda',
  path: '/maaliyadda',
  getParentRoute: () => AppRoute,
} as any)
const AppKalandarRoute = AppKalandarRouteImport.update({
  id: '/kalandar',
  path: '/kalandar',
  getParentRoute: () => AppRoute,
} as any)
const AppIsticmaalayaashaRoute = AppIsticmaalayaashaRouteImport.update({
  id: '/isticmaalayaasha',
  path: '/isticmaalayaasha',
  getParentRoute: () => AppRoute,
} as any)
const AppImtixaanadaRoute = AppImtixaanadaRouteImport.update({
  id: '/imtixaanada',
  path: '/imtixaanada',
  getParentRoute: () => AppRoute,
} as any)
const AppGaadiidkaRoute = AppGaadiidkaRouteImport.update({
  id: '/gaadiidka',
  path: '/gaadiidka',
  getParentRoute: () => AppRoute,
} as any)
const AppFasalladaRoute = AppFasalladaRouteImport.update({
  id: '/fasallada',
  path: '/fasallada',
  getParentRoute: () => AppRoute,
} as any)
const AppDacwoRoute = AppDacwoRouteImport.update({
  id: '/dacwo',
  path: '/dacwo',
  getParentRoute: () => AppRoute,
} as any)
const AppCasharkaRoute = AppCasharkaRouteImport.update({
  id: '/casharka',
  path: '/casharka',
  getParentRoute: () => AppRoute,
} as any)
const AppArdaydaRoute = AppArdaydaRouteImport.update({
  id: '/ardayda',
  path: '/ardayda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/ardayda': typeof AppArdaydaRoute
  '/casharka': typeof AppCasharkaRoute
  '/dacwo': typeof AppDacwoRoute
  '/fasallada': typeof AppFasalladaRoute
  '/gaadiidka': typeof AppGaadiidkaRoute
  '/imtixaanada': typeof AppImtixaanadaRoute
  '/isticmaalayaasha': typeof AppIsticmaalayaashaRoute
  '/kalandar': typeof AppKalandarRoute
  '/maaliyadda': typeof AppMaaliyaddaRoute
  '/reports': typeof AppReportsRoute
  '/shaqaalaha': typeof AppShaqaalahaRoute
  '/sifaynta': typeof AppSifayntaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ardayda': typeof AppArdaydaRoute
  '/casharka': typeof AppCasharkaRoute
  '/dacwo': typeof AppDacwoRoute
  '/fasallada': typeof AppFasalladaRoute
  '/gaadiidka': typeof AppGaadiidkaRoute
  '/imtixaanada': typeof AppImtixaanadaRoute
  '/isticmaalayaasha': typeof AppIsticmaalayaashaRoute
  '/kalandar': typeof AppKalandarRoute
  '/maaliyadda': typeof AppMaaliyaddaRoute
  '/reports': typeof AppReportsRoute
  '/shaqaalaha': typeof AppShaqaalahaRoute
  '/sifaynta': typeof AppSifayntaRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ardayda': typeof AppArdaydaRoute
  '/_app/casharka': typeof AppCasharkaRoute
  '/_app/dacwo': typeof AppDacwoRoute
  '/_app/fasallada': typeof AppFasalladaRoute
  '/_app/gaadiidka': typeof AppGaadiidkaRoute
  '/_app/imtixaanada': typeof AppImtixaanadaRoute
  '/_app/isticmaalayaasha': typeof AppIsticmaalayaashaRoute
  '/_app/kalandar': typeof AppKalandarRoute
  '/_app/maaliyadda': typeof AppMaaliyaddaRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/shaqaalaha': typeof AppShaqaalahaRoute
  '/_app/sifaynta': typeof AppSifayntaRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ardayda'
    | '/casharka'
    | '/dacwo'
    | '/fasallada'
    | '/gaadiidka'
    | '/imtixaanada'
    | '/isticmaalayaasha'
    | '/kalandar'
    | '/maaliyadda'
    | '/reports'
    | '/shaqaalaha'
    | '/sifaynta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ardayda'
    | '/casharka'
    | '/dacwo'
    | '/fasallada'
    | '/gaadiidka'
    | '/imtixaanada'
    | '/isticmaalayaasha'
    | '/kalandar'
    | '/maaliyadda'
    | '/reports'
    | '/shaqaalaha'
    | '/sifaynta'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/ardayda'
    | '/_app/casharka'
    | '/_app/dacwo'
    | '/_app/fasallada'
    | '/_app/gaadiidka'
    | '/_app/imtixaanada'
    | '/_app/isticmaalayaasha'
    | '/_app/kalandar'
    | '/_app/maaliyadda'
    | '/_app/reports'
    | '/_app/shaqaalaha'
    | '/_app/sifaynta'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sifaynta': {
      id: '/_app/sifaynta'
      path: '/sifaynta'
      fullPath: '/sifaynta'
      preLoaderRoute: typeof AppSifayntaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shaqaalaha': {
      id: '/_app/shaqaalaha'
      path: '/shaqaalaha'
      fullPath: '/shaqaalaha'
      preLoaderRoute: typeof AppShaqaalahaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maaliyadda': {
      id: '/_app/maaliyadda'
      path: '/maaliyadda'
      fullPath: '/maaliyadda'
      preLoaderRoute: typeof AppMaaliyaddaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalandar': {
      id: '/_app/kalandar'
      path: '/kalandar'
      fullPath: '/kalandar'
      preLoaderRoute: typeof AppKalandarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/isticmaalayaasha': {
      id: '/_app/isticmaalayaasha'
      path: '/isticmaalayaasha'
      fullPath: '/isticmaalayaasha'
      preLoaderRoute: typeof AppIsticmaalayaashaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imtixaanada': {
      id: '/_app/imtixaanada'
      path: '/imtixaanada'
      fullPath: '/imtixaanada'
      preLoaderRoute: typeof AppImtixaanadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaadiidka': {
      id: '/_app/gaadiidka'
      path: '/gaadiidka'
      fullPath: '/gaadiidka'
      preLoaderRoute: typeof AppGaadiidkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fasallada': {
      id: '/_app/fasallada'
      path: '/fasallada'
      fullPath: '/fasallada'
      preLoaderRoute: typeof AppFasalladaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dacwo': {
      id: '/_app/dacwo'
      path: '/dacwo'
      fullPath: '/dacwo'
      preLoaderRoute: typeof AppDacwoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casharka': {
      id: '/_app/casharka'
      path: '/casharka'
      fullPath: '/casharka'
      preLoaderRoute: typeof AppCasharkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ardayda': {
      id: '/_app/ardayda'
      path: '/ardayda'
      fullPath: '/ardayda'
      preLoaderRoute: typeof AppArdaydaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArdaydaRoute: typeof AppArdaydaRoute
  AppCasharkaRoute: typeof AppCasharkaRoute
  AppDacwoRoute: typeof AppDacwoRoute
  AppFasalladaRoute: typeof AppFasalladaRoute
  AppGaadiidkaRoute: typeof AppGaadiidkaRoute
  AppImtixaanadaRoute: typeof AppImtixaanadaRoute
  AppIsticmaalayaashaRoute: typeof AppIsticmaalayaashaRoute
  AppKalandarRoute: typeof AppKalandarRoute
  AppMaaliyaddaRoute: typeof AppMaaliyaddaRoute
  AppReportsRoute: typeof AppReportsRoute
  AppShaqaalahaRoute: typeof AppShaqaalahaRoute
  AppSifayntaRoute: typeof AppSifayntaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArdaydaRoute: AppArdaydaRoute,
  AppCasharkaRoute: AppCasharkaRoute,
  AppDacwoRoute: AppDacwoRoute,
  AppFasalladaRoute: AppFasalladaRoute,
  AppGaadiidkaRoute: AppGaadiidkaRoute,
  AppImtixaanadaRoute: AppImtixaanadaRoute,
  AppIsticmaalayaashaRoute: AppIsticmaalayaashaRoute,
  AppKalandarRoute: AppKalandarRoute,
  AppMaaliyaddaRoute: AppMaaliyaddaRoute,
  AppReportsRoute: AppReportsRoute,
  AppShaqaalahaRoute: AppShaqaalahaRoute,
  AppSifayntaRoute: AppSifayntaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
