/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppImtixaanadaRouteImport } from './routes/_app.imtixaanada'
import { Route as AppGaadiidkaRouteImport } from './routes/_app.gaadiidka'
import { Route as AppFasalladaRouteImport } from './routes/_app.fasallada'
import { Route as AppCasharkaRouteImport } from './routes/_app.casharka'
import { Route as AppArdaydaRouteImport } from './routes/_app.ardayda'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppImtixaanadaRoute = AppImtixaanadaRouteImport.update({
  id: '/imtixaanada',
  path: '/imtixaanada',
  getParentRoute: () => AppRoute,
} as any)
const AppGaadiidkaRoute = AppGaadiidkaRouteImport.update({
  id: '/gaadiidka',
  path: '/gaadiidka',
  getParentRoute: () => AppRoute,
} as any)
const AppFasalladaRoute = AppFasalladaRouteImport.update({
  id: '/fasallada',
  path: '/fasallada',
  getParentRoute: () => AppRoute,
} as any)
const AppCasharkaRoute = AppCasharkaRouteImport.update({
  id: '/casharka',
  path: '/casharka',
  getParentRoute: () => AppRoute,
} as any)
const AppArdaydaRoute = AppArdaydaRouteImport.update({
  id: '/ardayda',
  path: '/ardayda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ardayda': typeof AppArdaydaRoute
  '/casharka': typeof AppCasharkaRoute
  '/fasallada': typeof AppFasalladaRoute
  '/gaadiidka': typeof AppGaadiidkaRoute
  '/imtixaanada': typeof AppImtixaanadaRoute
}
export interface FileRoutesByTo {
  '/ardayda': typeof AppArdaydaRoute
  '/casharka': typeof AppCasharkaRoute
  '/fasallada': typeof AppFasalladaRoute
  '/gaadiidka': typeof AppGaadiidkaRoute
  '/imtixaanada': typeof AppImtixaanadaRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ardayda': typeof AppArdaydaRoute
  '/_app/casharka': typeof AppCasharkaRoute
  '/_app/fasallada': typeof AppFasalladaRoute
  '/_app/gaadiidka': typeof AppGaadiidkaRoute
  '/_app/imtixaanada': typeof AppImtixaanadaRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ardayda'
    | '/casharka'
    | '/fasallada'
    | '/gaadiidka'
    | '/imtixaanada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ardayda'
    | '/casharka'
    | '/fasallada'
    | '/gaadiidka'
    | '/imtixaanada'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ardayda'
    | '/_app/casharka'
    | '/_app/fasallada'
    | '/_app/gaadiidka'
    | '/_app/imtixaanada'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imtixaanada': {
      id: '/_app/imtixaanada'
      path: '/imtixaanada'
      fullPath: '/imtixaanada'
      preLoaderRoute: typeof AppImtixaanadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaadiidka': {
      id: '/_app/gaadiidka'
      path: '/gaadiidka'
      fullPath: '/gaadiidka'
      preLoaderRoute: typeof AppGaadiidkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fasallada': {
      id: '/_app/fasallada'
      path: '/fasallada'
      fullPath: '/fasallada'
      preLoaderRoute: typeof AppFasalladaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casharka': {
      id: '/_app/casharka'
      path: '/casharka'
      fullPath: '/casharka'
      preLoaderRoute: typeof AppCasharkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ardayda': {
      id: '/_app/ardayda'
      path: '/ardayda'
      fullPath: '/ardayda'
      preLoaderRoute: typeof AppArdaydaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArdaydaRoute: typeof AppArdaydaRoute
  AppCasharkaRoute: typeof AppCasharkaRoute
  AppFasalladaRoute: typeof AppFasalladaRoute
  AppGaadiidkaRoute: typeof AppGaadiidkaRoute
  AppImtixaanadaRoute: typeof AppImtixaanadaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArdaydaRoute: AppArdaydaRoute,
  AppCasharkaRoute: AppCasharkaRoute,
  AppFasalladaRoute: AppFasalladaRoute,
  AppGaadiidkaRoute: AppGaadiidkaRoute,
  AppImtixaanadaRoute: AppImtixaanadaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
